name: block
description: A flexible and efficient binary data handling library for Dart with segmented storage, zero-copy slices, and streaming support for optimal memory usage.
version: 0.0.4
repository: https://github.com/medz/block

topics:
  - binary
  - streams
  - data
  - blob
  - block

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  benchmark_harness: ^2.2.2
